package keymanager

import (
	"crypto/ed25519"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"os"
)

// encodePrivateKeyPEM serialises an Ed25519 private key into the PKCS#8 PEM
// form written to disk. Exposed so the staging path can build the same bytes
// the existing writer produces, without going through the size-capped reader.
func encodePrivateKeyPEM(key ed25519.PrivateKey) ([]byte, error) {
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return nil, fmt.Errorf("marshal Ed25519 private key: %w", err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der}), nil
}

// encodePublicKeyPEM serialises an Ed25519 public key into the PKIX PEM form
// written to disk.
func encodePublicKeyPEM(key ed25519.PublicKey) ([]byte, error) {
	der, err := x509.MarshalPKIXPublicKey(key)
	if err != nil {
		return nil, fmt.Errorf("marshal Ed25519 public key: %w", err)
	}
	//nolint:gosec // public key is intentionally world-readable
	return pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}), nil
}

// writeKeyFile creates path, writes data, fsyncs and closes it. Used by the
// staging path so the staged entries themselves survive a machine crash even
// before they are hard-linked into KeysDir.
func writeKeyFile(path string, data []byte, perm os.FileMode) error {
	// #nosec G304 -- path is KeysDir or a staging directory inside it; names are fixed or generated by stagingDirName
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, perm)
	if err != nil {
		return err
	}
	if _, err := f.Write(data); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}
