name: DCO

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  dco:
    uses: Glyndor/.github/.github/workflows/dco.yml@41d31f18d3ed3bb1a8cbbc44c68030e4867488b2 # v1.11.0
