name: Line limit

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  line-limit:
    uses: Glyndor/.github/.github/workflows/line-limit.yml@aba530bccc10ed0f1eb93b063824560ec9347ea7 # v1.3.0
