name: guard

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  develop-only:
    uses: Glyndor/.github/.github/workflows/main-guard.yml@aba530bccc10ed0f1eb93b063824560ec9347ea7 # v1.3.0
