name: guard

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  develop-only:
    uses: Glyndor/.github/.github/workflows/main-guard.yml@41d31f18d3ed3bb1a8cbbc44c68030e4867488b2 # v1.11.0
